# spring.application.name=demo
# Completely disable Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# H2 configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.error.include-message=always
# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Debug logging
logging.level.org.springframework.web=DEBUG